apiVersion: kustomize.config.gitops-multifile.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- deployment-reconciler.yaml
- service.yaml

images:
- name: nodeserver
  newName: igooruh/ocp-turbonomic-gitops-argo
  newTag: af37571912f0dd89cbff8d66ae50764937c6840f
