apiVersion: v1
kind: Service
metadata:
  name: application-gitops-service
  labels:
    app: application-simple-gitops
    app.kubernetes.io/instance: bb-gitops-pipeline-devops
spec:
  selector:
    app: application-simple-gitops
  ports:
    - port: 8080
      targetPort: 8080